# Run black and pylint in GitHub Actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: Check

on:
  - push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install black pylint
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
